name: Deploy to GCE

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: bootsoft
  GAR_LOCATION: asia-northeast1
  REPOSITORY: bootsoft-repo
  IMAGE: bootsoft-app
  INSTANCE_NAME: instance-1
  ZONE: asia-northeast1-a

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Docker Auth'
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and Push Container
        run: |-
          docker build \
            --build-arg RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }} \
            -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}" .
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"

      - name: Deploy to GCE
        run: |-
          gcloud compute instances update-container ${{ env.INSTANCE_NAME }} \
            --zone ${{ env.ZONE }} \
            --container-image "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}" \
            --container-env RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}